### ISSUE TITLE
MRB FAIL: pixel-perfect-deltas 7507c330fcd8152565d54c6aa0273587d3533be0

### ISSUE THREAD

**Issue by SimonBarnett** [SimonBarnett/bob-design-uat#34]
**Feature request:** https://github.com/SimonBarnett/bob-design-uat/issues/8

## Verdict

**FAIL**

SHA `7507c330fcd8152565d54c6aa0273587d3533be0` only (PR #25 head). This SHA's #8 acceptance is green **in isolation**. That is not enough.

`bob-hostile-mrb`: a GitHub `CONFLICTING` PR is FAIL even when this SHA's gates are green alone. PASS-nits includes `gh pr merge`. Immediately before this post: `mergeable=CONFLICTING`, `mergeStateStatus=DIRTY`, head still `7507c330`.

Cause: `main` moved under the review. `02292a1c223b3fab6301aebb58e510836b6c74f4` merged PR #26 (`loop-i7-build`, issue #7 T-S07). `git merge-tree origin/main 7507c330` conflicts in:

- `README.md`
- `docs/build-and-test-plan.md`
- `tools/Validate-DesignUatSkill.ps1`

Do not merge. Required fixes only. Dispatcher starts a **new** FIX worker on a new head. Do not reuse this FAIL issue as the next board.

No source PDF was supplied. None invented.

| Gate | Source | Isolation (7507c330 vs old main 46fac43) | Merge bar |
|------|--------|------------------------------------------|-----------|
| G2 px/hex on every row | #8 LOCKED; L4/L10; A7 G2 leg | GREEN. Skill **Deltas (#8)**; schema **G2 deltas (#8)**; example has both measurements. | Blocked. Cannot merge. |
| Pixel-perfect = listed deltas | #8 LOCKED | GREEN. Skill G2 matches issue lock. | Blocked. |
| Report columns / T-S08 needles | L5; A2; A3; plan P0b | GREEN vs 46fac43. BT0 exit 0 locally. Actions `validate` SUCCESS on this head. | Blocked. Validator now conflicts with #7 T-S07 needles on `main`. |
| FR parked on branch | #8 DoD | GREEN. `docs/feature-request-pixel-perfect-deltas-2026-09-22.md` on this SHA. | Must survive rebase with #7 FR. |
| PR title / no UAT stamp | #8 DoD | GREEN. Title includes `#8`. | N/A until MERGEABLE. |
| Mergeable | bob-hostile-mrb | **RED.** `CONFLICTING` / `DIRTY`. | **FAIL.** |
| L7 / N2 / secrets | MUST NOT | GREEN on this tree. Instructional warnings only. | Keep on FIX. |

## Feature request

https://github.com/SimonBarnett/bob-design-uat/issues/8

Intake on this head: `docs/feature-request-pixel-perfect-deltas-2026-09-22.md`

Plan: `docs/build-and-test-plan.md` â€” Definition of done (issue #8) + P0b T-S08.

Spec: `docs/functional-spec.md` L4 G2, L8, L10, A7.

Prior FAIL boards for this FR: none (this is the first).

## Missing features

This FR's acceptance is **green in isolation** and **red on the merge bar**. Do not open a second FR for the #8 MUST. The conflict is a Required fix on this board.

Already parked (issue + intake). Not in this PR. Do not duplicate. Dispatcher hands each remaining open `feature-request` to a **new** worker if none is running. This MRB does not implement them.

| Issue | Intake | Residual |
|-------|--------|----------|
| [#3](https://github.com/SimonBarnett/bob-design-uat/issues/3) golden + absorbed [#5](https://github.com/SimonBarnett/bob-design-uat/issues/5) | `docs/feature-request-golden-fixture-pack-2026-09-22.md` | No `fixtures/` on this SHA. T-G02 is remaining pixel proof for #8. Open FAIL #16 / #24. |
| [#2](https://github.com/SimonBarnett/bob-design-uat/issues/2) three visual gates | `docs/feature-request-three-gates-2026-09-22.md` | Open FAIL #23. PRs #18 / #27. |
| [#7](https://github.com/SimonBarnett/bob-design-uat/issues/7) G3 inventory | `docs/feature-request-hallucination-inventory-2026-09-22.md` | **Merged** via PR #26 onto `main`. This is what dirtied #25. Residual: #3 T-G03. |
| [#28](https://github.com/SimonBarnett/bob-design-uat/issues/28) harvest PDF/Illustrator/graphics | `docs/feature-request-harvest-pdf-illustrator-graphics-2026-09-22.md` | Adjacent. Not this SHA. |
| [#29](https://github.com/SimonBarnett/bob-design-uat/issues/29) companion skills | `docs/feature-request-pdf-illustrator-graphics-skills-2026-09-22.md` | Adjacent. Not this SHA. |

No unspecified hole required a **new** intake. U3 (G2 tolerance) and mock source stay UNKNOWN.

## Blockers

1. PR #25 is `CONFLICTING` / `DIRTY` against `main` `02292a1` (PR #26 / #7). `gh pr merge` cannot succeed. PASS-nits is void until a new head is MERGEABLE / CLEAN.

## Nits

(Do not treat these as the fail reason. The fail reason is the conflict.)

1. **T-S08 is still a slogan.** BT0 is `Test-Path` + `-match`. It does not parse a G2 row and fail a missing measurement. That proof is #3 T-G02.
2. **G2 intro still says "when visible."** The lock is every G2 row. **Deltas (#8)** carries the MUST.
3. **PR #25 test plan** leaves the Actions `validate` box unchecked. The job already passed on this head.
4. **Secret scan still skips schema and template.** This SHA added the #8 FR to `$scanFiles` only.
5. **README Open FRs** still lists closed #1 / #6 as live seats.
6. **Plan kickoff** still says open a PR for #1.
7. **Template** still puts `delta_px` / `delta_hex` on G1 rows. Skill says G2 only.

## Evidence

Reviewed **7507c330fcd8152565d54c6aa0273587d3533be0** only. Checkout `C:\ai\bob-design-uat-i8` is this head (`loop-i8-build`). Working tree clean. Did not stage, commit, rebase, or merge. Did not score later commits or dirty files.

**BT0** local on this SHA â€” exit 0 (isolation only):

```
Validate-DesignUatSkill: OK
```

Command: `powershell -NoProfile -ExecutionPolicy Bypass -File .\tools\Validate-DesignUatSkill.ps1`

**BT0 CI** on this head â€” Actions `validate` SUCCESS: https://github.com/SimonBarnett/bob-design-uat/actions/runs/35706735824/job/106677363009

**Merge-tree** vs current `origin/main` `02292a1`:

```
CONFLICT (content): Merge conflict in README.md
CONFLICT (content): Merge conflict in docs/build-and-test-plan.md
CONFLICT (content): Merge conflict in tools/Validate-DesignUatSkill.ps1
```

**PR immediately before this post:** `CONFLICTING` / `DIRTY` / head `7507c330fcd8152565d54c6aa0273587d3533be0`.

**Secrets:** tree grep `password=` / `XAI_API_KEY=` hits instructional L7 / skill warnings only.

**Not run:** live OCR (U1), fixture packs (#3), Figma (U2), `Install-DesignUatSkill.ps1`.

## Required fixes

1. Rebase or merge current `main` (`02292a1` / PR #26) onto this work. Resolve `README.md`, `docs/build-and-test-plan.md`, and `tools/Validate-DesignUatSkill.ps1`.
2. Union both landings: keep #7 T-S07 needles / FR / DoD **and** #8 T-S08 needles / FR / DoD. Do not drop either side.
3. BT0 exit 0 on the **new** head.
4. GitHub must report `MERGEABLE` / `CLEAN` on the new head. PASS-nits includes `gh pr merge`.

Do not implement those fixes in this MRB job.

## PR

https://github.com/SimonBarnett/bob-design-uat/pull/25

Head: `7507c330fcd8152565d54c6aa0273587d3533be0`

Title: `FR #8: G2 pixel-perfect deltas (px/hex) + BT0 T-S08`

Did not merge.

**Comment by SimonBarnett** [comment]
FIX PR: https://github.com/SimonBarnett/bob-design-uat/pull/36 (SHA 71f20c94bbf85ebdf66b854f389a5af04a261b96)

**Comment by SimonBarnett** [comment]
Hostile MRB of `71f20c94bbf85ebdf66b854f389a5af04a261b96` (PR #36): **PASS-nits** https://github.com/SimonBarnett/bob-design-uat/issues/41

**Comment by SimonBarnett** [comment]
Next board: https://github.com/SimonBarnett/bob-design-uat/issues/41 (SHA 71f20c94bbf85ebdf66b854f389a5af04a261b96)

**Comment by SimonBarnett** [comment]
PASS-nits #41 is VOID. Live FAIL for SHA `71f20c94`: https://github.com/SimonBarnett/bob-design-uat/issues/44

**Comment by SimonBarnett** [comment]
Prior FAIL closed after PASS-nits merge: https://github.com/SimonBarnett/bob-design-uat/pull/45
