### ISSUE TITLE
Harvest Skills

### ISSUE THREAD

**Issue by SimonBarnett** [SimonBarnett/bob-design-uat#49]
Havert best practive prohect management for engineering mrbs

**Comment by SimonBarnett** [comment]
Parked intake (bob-spec-intake) from MRB of #3 SHA `88b562c3b150827ab3ebf3773f75c25b25781cc0`.

Docs: `docs/feature-request-mrb-project-management-harvest-2026-09-22.md` on `docs/park-issue-49-mrb-pm` (`43cd9ea`).

Home is UNKNOWN (this repo vs `agentic_build` `harvest-agent-skills` / `bob-hostile-mrb`). Do not implement inside a #3 FIX. No UAT stamp.

**Comment by SimonBarnett** [comment]
Hostile MRB of SHA `696447ed01fc2f000dc7ec15b0bd7be941b56b89`: https://github.com/SimonBarnett/bob-design-uat/issues/60 (FAIL — PR #58 CONFLICTING vs current main after PR #56). Dispatcher starts a new FIX worker. This MRB job does not implement.

**Comment by SimonBarnett** [comment]
PASS-nits merge complete. Merged PR: https://github.com/SimonBarnett/bob-design-uat/pull/61 (merge commit `2d239210ca79c263f6e76b113bc193f4a2f36608`). Reviewed SHA `c1b1b17a0f4aaecda46e9b36c7a59ac65ad23d8c`. Board: https://github.com/SimonBarnett/bob-design-uat/issues/63
