### ISSUE TITLE
MRB FAIL: pixel-perfect-deltas 71f20c94bbf85ebdf66b854f389a5af04a261b96

### ISSUE THREAD

**Issue by SimonBarnett** [SimonBarnett/bob-design-uat#44]
**Feature request:** https://github.com/SimonBarnett/bob-design-uat/issues/8

## Verdict

**FAIL**

SHA `71f20c94bbf85ebdf66b854f389a5af04a261b96` only (PR #36 head). This SHA's #8 acceptance is green **in isolation vs the main it was merged with** (`02292a1` / PR #26). That is not enough.

`bob-hostile-mrb`: a GitHub `CONFLICTING` PR is FAIL even when this SHA's gates are green alone. PASS-nits includes `gh pr merge`. A stale `CLEAN` can go `DIRTY` while the board is written.

Board https://github.com/SimonBarnett/bob-design-uat/issues/41 posted **PASS-nits** while `mergeable=MERGEABLE` / `CLEAN`. Immediately before `gh pr merge`: GitHub flipped to `UNKNOWN`, then `CONFLICTING` / `DIRTY`. **Did not merge.** That PASS-nits is **void**. This issue is the live board for this SHA.

Cause: `main` moved under the review. `8c245db` merged PR #37 (`work/fix-issue-35-merge-main-i2`, issue #2 three-gates / FAIL #35). `git merge-tree origin/main 71f20c94` conflicts in:

- `.grok/skills/design-uat/SKILL.md`
- `docs/build-and-test-plan.md`

Do not merge. Required fixes only. Dispatcher starts a **new** FIX worker on a new head. Do not reuse this FAIL issue as the next board. Do not reuse voided #41.

No source PDF was supplied. None invented.

| Gate | Source | Isolation (71f20c94 vs old main 02292a1) | Merge bar vs 8c245db |
|------|--------|------------------------------------------|----------------------|
| G2 px/hex on every row | #8 LOCKED; L4/L10; A7 G2 leg | GREEN. Skill **Deltas (#8)**; schema **G2 deltas (#8)**. | Blocked. Cannot merge. |
| Pixel-perfect = listed deltas | #8 LOCKED | GREEN. | Blocked. |
| Report columns / T-S08 needles | L5; A2; A3; plan P0b | GREEN. Local BT0 exit 0. Actions `validate` SUCCESS on this head. | Blocked. Skill + plan now conflict with #2 three-gates landing. |
| FR parked on branch | #8 DoD | GREEN. #8 FR on this SHA. | Must survive rebase with #2 FR + #7 FR. |
| #7 union | FAIL #34 required fix | GREEN vs 02292a1. | Must survive union with #2. |
| Mergeable | bob-hostile-mrb | Was CLEAN at #41 post. | **RED.** `CONFLICTING` / `DIRTY`. |
| L7 / N2 / secrets | MUST NOT | GREEN. Instructional warnings only. | Keep on FIX. |

## Feature request

https://github.com/SimonBarnett/bob-design-uat/issues/8

Intake on this head: `docs/feature-request-pixel-perfect-deltas-2026-09-22.md`

Plan: `docs/build-and-test-plan.md` - Definition of done (issue #8) + P0b T-S08.

Spec: `docs/functional-spec.md` L4 G2, L8, L10, A7.

Prior boards for this FR:

- FAIL https://github.com/SimonBarnett/bob-design-uat/issues/34 (SHA `7507c330`, PR #25 `CONFLICTING` vs `02292a1`)
- VOID PASS-nits https://github.com/SimonBarnett/bob-design-uat/issues/41 (same SHA as this board; merge aborted)

## Missing features

This FR's acceptance is **green in isolation** and **red on the merge bar**. Do not open a second FR for the #8 MUST. The conflict is a Required fix on this board.

Already parked (issue + intake). Not in this PR. Do not duplicate. Dispatcher hands each remaining open `feature-request` to a **new** worker if none is running. This MRB does not implement them.

| Issue | Intake | Residual |
|-------|--------|----------|
| [#3](https://github.com/SimonBarnett/bob-design-uat/issues/3) golden + absorbed [#5](https://github.com/SimonBarnett/bob-design-uat/issues/5) | `docs/feature-request-golden-fixture-pack-2026-09-22.md` | No `fixtures/` on this SHA. T-G02 is remaining pixel proof for #8. Open FAIL #16 / #24 / #39. |
| [#2](https://github.com/SimonBarnett/bob-design-uat/issues/2) three visual gates | `docs/feature-request-three-gates-2026-09-22.md` | **Merged** via PR #37 onto `main`. This is what dirtied #36. Residual: scorecard/fail-closed text must be unioned, not dropped. |
| [#7](https://github.com/SimonBarnett/bob-design-uat/issues/7) G3 inventory | `docs/feature-request-hallucination-inventory-2026-09-22.md` | Merged via PR #26. On this head. Residual: #3 T-G03. |
| [#29](https://github.com/SimonBarnett/bob-design-uat/issues/29) companion skills | `docs/feature-request-pdf-illustrator-graphics-skills-2026-09-22.md` | Adjacent. Open FAIL #38. Not this SHA. |

No unspecified hole required a **new** intake. U3 (G2 tolerance) and mock source stay UNKNOWN.

## Blockers

1. PR #36 is `CONFLICTING` / `DIRTY` against `main` `8c245db` (PR #37 / #2). `gh pr merge` cannot succeed. Voided PASS-nits #41. Live board is this FAIL.

## Nits

(Do not treat these as the fail reason. The fail reason is the conflict.)

1. **T-S08 is still a slogan.** BT0 is `Test-Path` + `-match`. It does not parse a G2 row and fail a missing measurement. That proof is #3 T-G02.
2. **G2 intro still says "when visible."** The lock is every G2 row. **Deltas (#8)** carries the MUST.
3. **PR #36 test plan** never names T-S08 and says Bob chairs MRB on **#34**. Chair is **#8**.
4. **Secret scan still skips schema and template.**
5. **README Open FRs** still lists closed #1 / #6 / #7 as live seats.
6. **Plan kickoff** still says open a PR for #1.
7. **Template** still puts `delta_px` / `delta_hex` on G1 rows. Skill says G2 only.
8. **L8** lists the #8 FR and omits the #7 FR on this tree.
9. **PR #25** remains OPEN and `CONFLICTING` at `7507c330`.

## Evidence

Reviewed **71f20c94bbf85ebdf66b854f389a5af04a261b96** only. Checkout `C:\ai\bob-design-uat-i8` is this head (`work/6c2096db-merge-i7-i8`). Working tree clean. Did not stage, commit, rebase, or merge. Did not score later commits or dirty files.

**BT0** local on this SHA - exit 0 (isolation only):

```
Validate-DesignUatSkill: OK
```

Command: `powershell -NoProfile -ExecutionPolicy Bypass -File .\tools\Validate-DesignUatSkill.ps1`

**BT0 CI** on this head - Actions `validate` SUCCESS: https://github.com/SimonBarnett/bob-design-uat/actions/runs/35707502982/job/106679870582

**Merge-tree** vs current `origin/main` `8c245db` (PR #37):

```
CONFLICT (content): Merge conflict in .grok/skills/design-uat/SKILL.md
CONFLICT (content): Merge conflict in docs/build-and-test-plan.md
```

**PR immediately before this post:** `CONFLICTING` / `DIRTY` / head `71f20c94bbf85ebdf66b854f389a5af04a261b96`.

**Voided board:** https://github.com/SimonBarnett/bob-design-uat/issues/41 posted PASS-nits while CLEAN; `gh pr merge` was not run after DIRTY.

**Secrets:** tree grep `password=` / `XAI_API_KEY=` hits instructional L7 only.

**Not run:** live OCR (U1), fixture packs (#3), Figma (U2), `Install-DesignUatSkill.ps1`.

## Required fixes

1. Rebase or merge current `main` (`8c245db` / PR #37) onto this work. Resolve `.grok/skills/design-uat/SKILL.md` and `docs/build-and-test-plan.md`.
2. Union all three landings: keep #2 three-gates procedure/scorecard/fail-closed text **and** #7 T-S07 needles / FR / DoD **and** #8 T-S08 needles / FR / DoD. Do not drop any side. #2's "Procedure (issue #2)", unread-text FAIL, G1/G2/G3 scorecard, and recorded-delta FAIL must survive next to **Deltas (#8)**.
3. BT0 exit 0 on the **new** head.
4. GitHub must report `MERGEABLE` / `CLEAN` on the new head. PASS-nits includes `gh pr merge`. Re-read `mergeable` immediately before posting PASS-nits; `main` is moving.

Do not implement those fixes in this MRB job.

## PR

https://github.com/SimonBarnett/bob-design-uat/pull/36

Head: `71f20c94bbf85ebdf66b854f389a5af04a261b96`

Title: `Fix issue #34: merge main #7 T-S07 with issue #8 G2 deltas`

Did not merge.

**Comment by SimonBarnett** [comment]
Prior FAIL closed after PASS-nits merge: https://github.com/SimonBarnett/bob-design-uat/pull/45
