### ISSUE TITLE
MRB FAIL: playwright-visual-uat 1d409b7fcc695c6dd7e5e45b21a8937697aeb317

### ISSUE THREAD

**Issue by SimonBarnett** [SimonBarnett/bob-design-uat#65]
**Feature request:** https://github.com/SimonBarnett/bob-design-uat/issues/57

## Verdict

FAIL

Reviewed SHA `1d409b7fcc695c6dd7e5e45b21a8937697aeb317` only. Isolated worktree at that SHA. Did not score later commits or dirty files on the shared checkout.

Isolated A-P1â€“A-P4 are green. PASS-nits includes `gh pr merge`. GitHub on PR https://github.com/SimonBarnett/bob-design-uat/pull/62 immediately before this post: `mergeable=CONFLICTING`, `mergeStateStatus=DIRTY`, `headRefOid=1d409b7fcc695c6dd7e5e45b21a8937697aeb317`, `baseRefOid=8d78f1977713f468eefed98dcd7336503764ca13`.

`origin/main` moved to `2d239210ca79c263f6e76b113bc193f4a2f36608` (PR #61 / issue #60 merge-main for #49) while this head still sits on `8d78f19`. `git merge-base --is-ancestor origin/main HEAD` is false. `git merge-tree` reports **changed in both** on five files. A CONFLICTING PR is FAIL even when this SHA's acceptance is green in isolation.

## Feature request

- Issue: https://github.com/SimonBarnett/bob-design-uat/issues/57
- Doc: `docs/feature-request-playwright-visual-uat-2026-09-22.md` (this SHA)
- Plan: `docs/build-and-test-plan-playwright-visual-uat.md` (dispatch park; DoD also folded into `docs/build-and-test-plan.md` on this SHA)
- Parked PDF: none supplied

Acceptance vs this SHA (isolated â€” not the merge gate):

| ID | Result | Note |
|----|--------|------|
| A-P1 | green isolated | `.grok/skills/playwright-design/SKILL.md` exists; YAML `name: playwright-design` |
| A-P2 | green isolated | Procedure: capture stills, then `design-uat` G1â€“G3. Skill forbids a worker UAT stamp |
| A-P3 | green isolated | `Install-DesignUatSkill.ps1` copies `playwright-design`. Isolated BT0 `Validate-DesignUatSkill: OK` exit 0 |
| A-P4 | green isolated | `design-uat` companion table lists `playwright-design`. Related-skills row in `docs/functional-spec.md`. No secret assignments |

MUST 1â€“6 match the isolated table. Plan T-P01â€“T-P06 green in isolation. DoD on this SHA (isolated): FR file, skill, install, BT0 needles, PR title `#57`, BT0 summary on the PR, no UAT stamp in the PR body.

MUST NOT (isolated): did not second-take #2 / #3 / #6 / #7 / #8 / #29 companion bodies; did not implement inside a #3 FIX; did not push `main`; did not merge own PR. `git grep` on SHA: `password=` / `XAI_API_KEY` only as instructional warnings.

## Missing features

This FR's isolated acceptance is green. The red item is the merge gate (Required fixes). No second FR for the same MUST.

Already parked issues that were open at review start and are now closed on `origin/main` via PR https://github.com/SimonBarnett/bob-design-uat/pull/61 (do not duplicate):

- https://github.com/SimonBarnett/bob-design-uat/issues/49 â€” Harvest Skills / MRB project-management â€” intake `docs/feature-request-mrb-project-management-harvest-2026-09-22.md` is on `origin/main`. Not this PR.

No unspecified hole that needs a new intake. This FR is capture + skill home, not a second golden pack and not a Playwright runner/config. Out of scope stays out of scope (Figma U2, inventing product routes, replacing the #3 fixture pack).

Remaining open `feature-request` after this FAIL: #57 only. Dispatcher starts a FIX worker for this board's Required fixes. This MRB job does not implement them.

## Blockers

1. **Merge gate.** PR #62 is `CONFLICTING` / `DIRTY` vs current `origin/main` `2d239210ca79c263f6e76b113bc193f4a2f36608` (merged PR https://github.com/SimonBarnett/bob-design-uat/pull/61). `git merge-tree` **changed in both**: `.grok/skills/design-uat/SKILL.md`, `docs/build-and-test-plan.md`, `docs/functional-spec.md`, `tools/Install-DesignUatSkill.ps1`, `tools/Validate-DesignUatSkill.ps1`. Main added `mrb-project-management` skill, #49 FR Require-File, install name, BT0 `$mrbPm` needle loop, and companion/spec/plan rows. This SHA added `playwright-design` in the same five files. Isolated BT0 is not the merge gate.

## Nits

Do not block a later PASS-nits once the merge gate is green. Listed so the FIX does not pretend the tree is tidy.

- Parked FR on the dispatch checkout uses real en/em dashes. This SHA's copy of `docs/feature-request-playwright-visual-uat-2026-09-22.md` mojibakes those bytes (`Ã”Ã‡Ã¶` / `Ã”Ã‡Ã´` under Windows-1252). Text is still readable. BT0 does not lock encoding.
- Dispatch plan `docs/build-and-test-plan-playwright-visual-uat.md` is not on this SHA. Worker folded #57 DoD into `docs/build-and-test-plan.md` instead. Acceptance still maps. The dedicated plan file is a dispatch artifact, not A-P1â€“A-P4.
- Capture rule says no live customer production URLs *unless the brief names them*, while Inputs already restrict to local/staging. Softens the MUST NOT. Procedure still forbids PII and invented routes. Not a red MUST.
- README Open FRs table still lists #2 / #3 / #6 / #7 / #8 with stale talk locks. Worker only appended #57. Pre-existing rot, not a second-take of those FRs.
- Skill names Playwright as the capture tool but ships no version pin, `npx` line, or `tools/*.ps1` wrapper. In scope for a skill-home FR; thin, not a missing MUST.
- Live `Install-DesignUatSkill.ps1` was not run into the user skills tree (would overwrite the box install). Script read: `$names` includes `playwright-design`.

## Evidence

Reviewed SHA only: `1d409b7fcc695c6dd7e5e45b21a8937697aeb317` (Add playwright-design companion skill for issue #57). Isolated worktree `D:\ai\bob-design-uat-i57-mrb-1d409b7`. Shared checkout HEAD was `0e49f2e` (park-only, not scored).

- Diff vs old `origin/main` `8d78f19`: 8 files, +147/âˆ’8. Added skill + FR. Install, BT0, `design-uat`, functional-spec, README, plan DoD.
- Did not second-take companion skill bodies. Isolated `design-uat` change is the required companion row + one sentence.
- Local BT0 on SHA (pre-main-move): `Validate-DesignUatFixtures: OK` then `Validate-DesignUatSkill: OK` exit 0
- CI on PR #62 (against stale base `8d78f19`): workflow `validate` SUCCESS (runs 35710375340, 35710418177); GitGuardian SUCCESS
- `git grep` on SHA: password / XAI_API_KEY only as instructional warnings. No assignments.
- Install script read on SHA: `$names` includes `playwright-design`
- `gh pr view 62` immediately before this post: headRefOid=`1d409b7fcc695c6dd7e5e45b21a8937697aeb317`, baseRefOid=`8d78f1977713f468eefed98dcd7336503764ca13`, mergeable=CONFLICTING, mergeStateStatus=DIRTY
- `git merge-base --is-ancestor origin/main 1d409b7` false. Current `origin/main`: `2d239210ca79c263f6e76b113bc193f4a2f36608` Merge pull request #61
- `git merge-tree` merge-base `8d78f19`: changed in both on the five files listed under Blockers. `playwright-design` skill + FR are added-in-remote (keep). README merged clean.
- Not run: live install into the user skills tree. No Playwright browser capture (FR is skill home, not a runner). BT1/BT2 remain manual issue #1 walkthroughs; not claimed done by this SHA.

## Required fixes

1. Merge current `origin/main` (`2d239210ca79c263f6e76b113bc193f4a2f36608`, PR #61 / issue #60) into the #57 branch. Do not replay this SHA on stale `8d78f19`.
2. Union `tools/Validate-DesignUatSkill.ps1`: keep this SHA's #57 Require-File, skill needle `playwright-design`, companion `$pair` row, and secret-scan path. Keep main's #49 Require-File, `mrb-project-management` skill needle, `$mrbPm` loop, and harvest FR Require-File. Do not drop T-S07 / T-S08 / fixture / companion locks.
3. Union `tools/Install-DesignUatSkill.ps1` `$names`: keep both `playwright-design` and `mrb-project-management`.
4. Union `.grok/skills/design-uat/SKILL.md` companion table: keep the `playwright-design` row from this SHA and the `mrb-project-management` row from main.
5. Union `docs/functional-spec.md` and `docs/build-and-test-plan.md` the same way (keep #57 Related / DoD and main's #49 Related / DoD).
6. After union: BT0 exit 0 on the new head; `git merge-base --is-ancestor origin/main HEAD` true; GitHub `mergeable=MERGEABLE` and `mergeStateStatus=CLEAN` on the new PR head. Hand off a new MRB on that SHA.

Do not implement these in this MRB job. Dispatcher starts a new FIX worker.

## PR

https://github.com/SimonBarnett/bob-design-uat/pull/62 (head `1d409b7fcc695c6dd7e5e45b21a8937697aeb317`). This board scores that SHA only.

**Comment by SimonBarnett** [comment]
Superseded by PASS-nits https://github.com/SimonBarnett/bob-design-uat/issues/67. Required merge-gate fixes landed in https://github.com/SimonBarnett/bob-design-uat/pull/66.

**Comment by SimonBarnett** [comment]
PASS-nits board https://github.com/SimonBarnett/bob-design-uat/issues/68. Merged https://github.com/SimonBarnett/bob-design-uat/pull/66 (3c630f86). This FAIL is closed.

**Comment by SimonBarnett** [comment]
PASS-nits https://github.com/SimonBarnett/bob-design-uat/issues/70. Merged https://github.com/SimonBarnett/bob-design-uat/pull/66 (3c630f86). Prior FAIL merge-gate required fixes landed on that merge.
